# Generated by Django 5.0.1 on 2024-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_postimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="feed.hashtag"
            ),
        ),
    ]
