# Generated by Django 5.0.1 on 2024-02-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0003_alter_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
