# Generated by Django 5.0.1 on 2024-02-04 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_alter_hashtag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Hashtag doesnt comply", regex="^[\\w]*$"
                    )
                ],
            ),
        ),
    ]
