# Generated by Django 5.0.1 on 2024-02-07 21:26

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user.models.profile_image_file_path,
            ),
        ),
    ]
